apiVersion: v1
kind: Pod
metadata:
  name: image-volume-custom
spec:
  containers:
  - name: shell
    command: ["sleep", "infinity"]
    image: debian
    volumeMounts:
    - name: volume
      mountPath: /volume
  volumes:
  - name: volume
    image:
      reference: customimagevolume:v1
      pullPolicy: IfNotPresent
